### ISSUE TITLE
Sync fails if the site name contains dashes in gdev create

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/gdev#45]
I created a new site with the `gdev create` wizard and set a site name that contained dashes. Sync failed because of replacements made into the template docker configuration files of [wp-project](https://github.com/devgeniem/wp-project). The dashes were removed in them. I put the dashes back in `docker-composer.yml` and `docker-sync.yml`, reloaded everything and the sync started to work.

Here is an example of a functioning sync config file:
```
version: "2"

options:
  verbose: true
syncs:
  my-site-name-with-dashes-sync:
    src: '.'
    host_disk_mount_mode: 'cached'
  my-site-name-with-dashes-uploads-sync:
    src: './.docker/uploads'
    host_disk_mount_mode: 'cached'
```
